name: farm-demo
recipe: pantheon
config:
  framework: drupal8
  site: farm-demo
  id: 3a0f40fe-f733-4022-98e3-8cf7a0b4635c
services:
  appserver:
    xdebug: true
    config:
      php: xdebug.ini
    build:
      - composer install
    scanner: false
    overrides:
      environment:
        SIMPLETEST_BASE_URL: 'http://farm-demo.lndo.site'
        SIMPLETEST_DB: 'mysql://root:@database/database'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
        PHP_IDE_CONFIG: 'serverName=appserver'
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
    overrides:
      environment:
        UPLOAD_LIMIT: 25600000
    hosts:
      - database
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  test:
    service: appserver
    cmd: 'php /app/vendor/bin/phpunit -c /app/phpunit.xml'
proxy:
  mailhog:
    - mail-farm-demo.lndo.site
  phpmyadmin:
    - db-farm-demo.lndo.site
