<?php

/**
 * @file
 * Primary module hooks for Farm Page module.
 */

/**
 * For myFarm function work correctly.
 */
function farm_page_theme() {
  return [
    'farm_homepage' => [
      'template' => 'farm-homepage',
      'variables' => [
        'data' => [],
      ],
    ],
    'list_farm' => [
      'template' => 'list-farm',
      'variables' => [
        'data' => [],
      ],
    ],
    'farm_product' => [
      'template' => 'farm-product',
      'variables' => [
        'data' => [],
      ],
    ],
    'farm_page_views_farms' => [
      'template' => 'farm-page-views-farms',
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function farm_page_preprocess_page(&$variables) {
  // Attach the library to the page template.
  $variables['#attached']['library'][] = 'farm_page/farm_page';
}
