<?php

/**
 * @file
 * Primary module hooks for Farm Page module.
 */

/**
 * For myFarm function work correctly.
 */
function farm_page_theme() {
  return [
    'farm_homepage' => [
      'template' => 'farm-homepage',
      'variables' => [
        'store' => 'No value',
        'products' => 'Store has no product',
        'store_images' => 'No images',
        'message' => '404 not found',
        'is_exist' => FALSE,
      ],
    ],
  ];
}
