_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 78fdc17d-2be7-4bac-bb0b-37b78ec86dea
name: Farm
mail: farm@yopmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /farms
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
