#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

./vendor/bin/phpcbf --standard=Drupal -v --extensions=php,inc,module,theme --ignore=node_modules,vendor/*,web/core/*,web/vendor/*,web/modules/contrib/* ./web/modules/custom

exit 0